// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLanguageDetail(arg1) {
  return window['go']['main']['App']['GetLanguageDetail'](arg1);
}

export function GetLanguageNames() {
  return window['go']['main']['App']['GetLanguageNames']();
}

export function GetMonth() {
  return window['go']['main']['App']['GetMonth']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetProjectDetail(arg1) {
  return window['go']['main']['App']['GetProjectDetail'](arg1);
}

export function GetProjectNames() {
  return window['go']['main']['App']['GetProjectNames']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetToday() {
  return window['go']['main']['App']['GetToday']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWeek() {
  return window['go']['main']['App']['GetWeek']();
}

export function GetYear(arg1) {
  return window['go']['main']['App']['GetYear'](arg1);
}
