// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLanguageDetail(arg1:string):Promise<main.DetailResponse>;

export function GetLanguageNames():Promise<Array<main.ItemData>>;

export function GetMonth():Promise<main.SummaryData>;

export function GetProfile():Promise<main.ProfileResponse>;

export function GetProjectDetail(arg1:string):Promise<main.DetailResponse>;

export function GetProjectNames():Promise<Array<main.ItemData>>;

export function GetStatus():Promise<main.StatusData>;

export function GetToday():Promise<main.SummaryData>;

export function GetVersion():Promise<string>;

export function GetWeek():Promise<main.SummaryData>;

export function GetYear(arg1:number):Promise<main.SummaryData>;
